server:
  port: 9090

spring:

  cloud:

    gateway:

      routes:

        # USER SERVICE
        - id: user-service

          uri: lb://USER-SERVICE

          predicates:
            - Path=/users/**

        # ORDER SERVICE
        - id: order-service

          uri: lb://ORDER-SERVICE

          predicates:
            - Path=/order/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"